In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [7]:
df = pd.read_csv('dataset.csv', encoding='utf-8').drop(columns=['Unnamed: 0'])
df = df[df['Year']==109]
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1488 entries, 2976 to 4463
Data columns (total 96 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   Year                                              1488 non-null   int64
 1   County Name                                       1488 non-null   object
 2   Township Name                                     1488 non-null   object
 3   Village Name                                      1488 non-null   object
 4   c_pop_Population                                  1488 non-null   float64
 5   c_ratio_Sex Ratio                                 1488 non-null   float64
 6   c_popcal_Population Density                       1488 non-null   float64
 7   c_ratio_Dependency Ratio                          1488 non-null   float64
 8   c_ratio_Child Dependency Ratio                    1488 non-null   float64
 9   c_ratio_Elderly Dependency Ratio                  1488 non-null   float64
 10  c_ratio_Aging Index                               1488 non-null   float64
 11  c_pop_Population aged 0-14                        1488 non-null   float64
 12  c_pop_Population aged 15-64                       1488 non-null   float64
 13  c_pop_Population aged 65 and above                1488 non-null   float64
 14  j_edu_15 with Doctorate Degree                    1488 non-null   float64
 15  j_edu_15 with Master Degree                       1488 non-null   float64
 16  j_edu_15 with University Education                1488 non-null   float64
 17  j_edu_15 with Vocational Education                1488 non-null   float64
 18  j_edu_15 with Senior High School Education        1488 non-null   float64
 19  j_edu_15 with Junior High School Education        1488 non-null   float64
 20  j_edu_15 with Elementary School Education         1488 non-null   float64
 21  j_edu_15 with Self-Taught Education               1488 non-null   float64
 22  j_edu_15 who are Illiterate                       1488 non-null   float64
 23  c_marrital_15 who are Unmarried                   1488 non-null   float64
 24  c_marrital_15 who are Married                     1488 non-null   float64
 25  c_marrital_15 who are Divorced                    1488 non-null   float64
 26  c_popcal_Natural Increase                         1488 non-null   float64
 27  c_popcal_Social Increase                          1488 non-null   float64
 28  c_popcal_Total Number of Households               1488 non-null   float64
 29  j_income_Total Comprehensive Income               1488 non-null   float64
 30  j_income_Average Comprehensive Income             1488 non-null   float64
 31  j_income_Median Comprehensive Income              1488 non-null   float64
 32  j_income_Comprehensive Income Q1                  1488 non-null   float64
 33  j_income_Comprehensive Income Q3                  1488 non-null   float64
 34  j_income_Comprehensive Income std                 1488 non-null   float64
 35  j_income_Total Amount of Various Types of Income  1488 non-null   float64
 36  j_income_Income from Wages and Salaries           1488 non-null   float64
 37  h_Median Housing Price with parking space         1488 non-null   float64
 38  h_Median Housing Price no parking space           1488 non-null   float64
 39  ht_NO2                                            1488 non-null   float64
 40  ht_PM2.5                                          1488 non-null   float64
 41  e_Water                                           1488 non-null   float64
 42  e_Green                                           1488 non-null   float64
 43  cs_trans_Metro 300                                1488 non-null   float64
 44  cs_trans_Metro 300 Multi                          1488 non-null   float64
 45  cs_trans_Metro 500                                1488 non-null   float64
 46  cs_trans_Metro 500 Multi                          1488 non-null   float64
 47  s_Fire                                            1488 non-null   float64
 48  s_Police                                          1488 non-null   float64
 49  cs_school_Primary                                 1488 non-null   float64
 50  cs_school_Secondary                               1488 non-null   float64
 51  cs_leisure_Gym                                    1488 non-null   float64
 52  e_Area                                            1488 non-null   float64
 53  ht_Hospital                                       1488 non-null   float64
 54  s_Shelter                                         1488 non-null   float64
 55  County Name_1                                     1488 non-null   float64
 56  Township Name_三峽區                                 1488 non-null   float64
 57  Township Name_三芝區                                 1488 non-null   float64
 58  Township Name_三重區                                 1488 non-null   float64
 59  Township Name_中和區                                 1488 non-null   float64
 60  Township Name_五股區                                 1488 non-null   float64
 61  Township Name_八里區                                 1488 non-null   float64
 62  Township Name_土城區                                 1488 non-null   float64
 63  Township Name_坪林區                                 1488 non-null   float64
 64  Township Name_平溪區                                 1488 non-null   float64
 65  Township Name_新店區                                 1488 non-null   float64
 66  Township Name_新莊區                                 1488 non-null   float64
 67  Township Name_板橋區                                 1488 non-null   float64
 68  Township Name_林口區                                 1488 non-null   float64
 69  Township Name_樹林區                                 1488 non-null   float64
 70  Township Name_永和區                                 1488 non-null   float64
 71  Township Name_汐止區                                 1488 non-null   float64
 72  Township Name_泰山區                                 1488 non-null   float64
 73  Township Name_淡水區                                 1488 non-null   float64
 74  Township Name_深坑區                                 1488 non-null   float64
 75  Township Name_烏來區                                 1488 non-null   float64
 76  Township Name_瑞芳區                                 1488 non-null   float64
 77  Township Name_石碇區                                 1488 non-null   float64
 78  Township Name_石門區                                 1488 non-null   float64
 79  Township Name_萬里區                                 1488 non-null   float64
 80  Township Name_蘆洲區                                 1488 non-null   float64
 81  Township Name_貢寮區                                 1488 non-null   float64
 82  Township Name_金山區                                 1488 non-null   float64
 83  Township Name_雙溪區                                 1488 non-null   float64
 84  Township Name_鶯歌區                                 1488 non-null   float64
 85  Township Name_中山區                                 1488 non-null   float64
 86  Township Name_中正區                                 1488 non-null   float64
 87  Township Name_信義區                                 1488 non-null   float64
 88  Township Name_內湖區                                 1488 non-null   float64
 89  Township Name_北投區                                 1488 non-null   float64
 90  Township Name_南港區                                 1488 non-null   float64
 91  Township Name_士林區                                 1488 non-null   float64
 92  Township Name_大同區                                 1488 non-null   float64
 93  Township Name_大安區                                 1488 non-null   float64
 94  Township Name_文山區                                 1488 non-null   float64
 95  Township Name_松山區                                 1488 non-null   float64
dtypes: float64(92), int64(1), object(3)
memory usage: 1.1+ MB

In [10]:
shp = pd.read_csv('toshp.csv', encoding='utf-8')
shp = shp.set_index(shp[['COUNTY', 'TOWN', 'VILLAGE']].apply(
        lambda x: "".join(x.astype(str)), axis=1))
shp.index.rename('index', inplace=True)

In [8]:
cal = df.iloc[:, 6:55].drop(columns=df.iloc[:,29:37].columns).drop(columns=['c_popcal_Total Number of Households', 'e_Area'])
cal['j_income_Comprehensive Income Q3'] = df['j_income_Comprehensive Income Q3']
cal.columns

Index(['c_popcal_Population Density', 'c_ratio_Dependency Ratio',
       'c_ratio_Child Dependency Ratio', 'c_ratio_Elderly Dependency Ratio',
       'c_ratio_Aging Index', 'c_pop_Population aged 0-14',
       'c_pop_Population aged 15-64', 'c_pop_Population aged 65 and above',
       'j_edu_15 with Doctorate Degree', 'j_edu_15 with Master Degree',
       'j_edu_15 with University Education',
       'j_edu_15 with Vocational Education',
       'j_edu_15 with Senior High School Education',
       'j_edu_15 with Junior High School Education',
       'j_edu_15 with Elementary School Education',
       'j_edu_15 with Self-Taught Education', 'j_edu_15 who are Illiterate',
       'c_marrital_15 who are Unmarried', 'c_marrital_15 who are Married',
       'c_marrital_15 who are Divorced', 'c_popcal_Natural Increase',
       'c_popcal_Social Increase', 'h_Median Housing Price with parking space',
       'h_Median Housing Price no parking space', 'ht_NO2', 'ht_PM2.5',
       'e_Water', 'e_Green', 'cs_trans_Metro 300', 'cs_trans_Metro 300 Multi',
       'cs_trans_Metro 500', 'cs_trans_Metro 500 Multi', 's_Fire', 's_Police',
       'cs_school_Primary', 'cs_school_Secondary', 'cs_leisure_Gym',
       'ht_Hospital', 's_Shelter', 'j_income_Comprehensive Income Q3'],
      dtype='object')

In [9]:
w = [-1,0,0,0,0,1,1,-1,1,1,1,-1,-1,-1,-1,-1,-1,-1,1,-1,1,1,-1,-1,-1,-1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]
w = w[::-1]
cal['QoL'] = 0
for i in cal.columns[:-1]:
    cal[i] = cal[i]*w.pop()
    cal['QoL'] = cal['QoL']+cal[i]
cal

,c_popcal_Population Density,c_ratio_Dependency Ratio,c_ratio_Child Dependency Ratio,c_ratio_Elderly Dependency Ratio,c_ratio_Aging Index,c_pop_Population aged 0-14,c_pop_Population aged 15-64,c_pop_Population aged 65 and above,j_edu_15 with Doctorate Degree,j_edu_15 with Master Degree,...,cs_trans_Metro 500 Multi,s_Fire,s_Police,cs_school_Primary,cs_school_Secondary,cs_leisure_Gym,ht_Hospital,s_Shelter,j_income_Comprehensive Income Q3,QoL
2976,-0.086318,0.0,0.0,0.0,0.0,0.007198,0.006503,-0.015566,0.000000,0.005402,...,0.0,1.0,1.0,1.0,1.0,0.0,0.285714,0.000000,0.137295,4.608731
2977,-0.041770,0.0,0.0,0.0,0.0,0.097172,0.147891,-0.101003,0.018824,0.042262,...,0.0,1.0,1.0,1.0,1.0,0.0,0.285714,0.003876,0.185963,4.104684
2978,-0.045966,0.0,0.0,0.0,0.0,0.110883,0.231368,-0.194051,0.028235,0.050524,...,0.0,1.0,1.0,1.0,1.0,0.0,0.142857,0.003876,0.120902,2.616301
2979,-0.015493,0.0,0.0,0.0,0.0,0.068038,0.155171,-0.149083,0.023529,0.043216,...,0.0,0.0,1.0,0.0,0.0,0.0,0.000000,0.000000,0.129098,0.260117
2980,-0.000505,0.0,0.0,0.0,0.0,0.011140,0.029289,-0.061224,0.002353,0.001907,...,0.0,0.0,1.0,0.0,0.0,0.0,0.000000,0.003876,0.042520,0.615132
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4459,-0.321954,0.0,0.0,0.0,0.0,0.102314,0.209971,-0.362158,0.058824,0.089927,...,0.0,1.0,1.0,1.0,1.0,0.0,0.142857,0.139535,0.212602,2.621979
4460,-0.247696,0.0,0.0,0.0,0.0,0.102828,0.173512,-0.273262,0.094118,0.116301,...,0.0,1.0,1.0,1.0,1.0,0.0,0.285714,0.306202,0.334016,3.975695
4461,-0.148354,0.0,0.0,0.0,0.0,0.085518,0.220030,-0.428917,0.068235,0.102637,...,0.0,1.0,1.0,1.0,0.0,0.0,0.285714,0.465116,0.247951,3.742633
4462,-0.360777,0.0,0.0,0.0,0.0,0.120480,0.264658,-0.497752,0.077647,0.165872,...,0.0,1.0,1.0,1.0,1.0,0.0,0.285714,0.379845,0.262295,2.571129
4463,-0.050666,0.0,0.0,0.0,0.0,0.045930,0.109265,-0.227949,0.054118,0.071497,...,0.0,1.0,1.0,1.0,1.0,0.0,0.428571,0.046512,0.271516,4.404452

In [20]:
qol = df.iloc[:,1:4].join(cal['QoL'])
qol[['Child Dependency Ratio', 'Elderly Dependency Ratio', 'Social Increase', 'Average Income', 'Metro 300 Multi', 'Metro 500 Multi']] = df.iloc[:, [8,9, 27,30,44,46]]
qol = qol.set_index(qol[['County Name', 'Township Name', 'Village Name']].apply(
        lambda x: "".join(x.astype(str)), axis=1))
qol.index.rename('index', inplace=True)
qol = qol.join(shp['V_ID'], on='index')
qol

,County Name,Township Name,Village Name,QoL,Child Dependency Ratio,Elderly Dependency Ratio,Social Increase,Average Income,Metro 300 Multi,Metro 500 Multi,V_ID
index,,,,,,,,,,,
新北市三峽區三峽里,新北市,三峽區,三峽里,4.608731,0.457689,0.495806,0.215674,0.094952,0.0,0.0,65000090-001
新北市三峽區中埔里,新北市,三峽區,中埔里,4.104684,0.452853,0.046582,0.285237,0.113782,0.0,0.0,65000090-004
新北市三峽區中正里,新北市,三峽區,中正里,2.616301,0.322292,0.084954,0.208384,0.056490,0.0,0.0,65000090-025
新北市三峽區二鬮里,新北市,三峽區,二鬮里,0.260117,0.287959,0.122970,0.205346,0.059696,0.0,0.0,65000090-026
新北市三峽區五寮里,新北市,三峽區,五寮里,0.615132,0.214458,0.439586,0.212940,0.017228,0.0,0.0,65000090-014
...,...,...,...,...,...,...,...,...,...,...,...
臺北市萬華區錦德里,臺北市,萬華區,錦德里,2.621979,0.327611,0.333750,0.186513,0.110176,0.0,0.0,63000070-025
臺北市萬華區雙園里,臺北市,萬華區,雙園里,3.975695,0.406190,0.292700,0.188032,0.192308,0.0,0.0,63000070-012
臺北市萬華區青山里,臺北市,萬華區,青山里,3.742633,0.252418,0.396573,0.214763,0.154247,0.0,0.0,63000070-006
臺北市萬華區頂碩里,臺北市,萬華區,頂碩里,2.571129,0.304642,0.376941,0.161300,0.145032,0.0,0.0,63000070-011
臺北市萬華區騰雲里,臺北市,萬華區,騰雲里,4.404452,0.270551,0.435481,0.201701,0.165064,0.0,0.0,63000070-036

In [22]:
for i in ['Child Dependency Ratio', 'Elderly Dependency Ratio', 'Social Increase', 'Average Income']:
    qol[i]= pd.qcut(qol[i], q=5, labels=[0.1, 0.2, 0.3, 0.4, 0.5])
qol

,County Name,Township Name,Village Name,QoL,Child Dependency Ratio,Elderly Dependency Ratio,Social Increase,Average Income,Metro 300 Multi,Metro 500 Multi,V_ID
index,,,,,,,,,,,
新北市三峽區三峽里,新北市,三峽區,三峽里,4.608731,0.5,0.5,0.4,0.2,0.0,0.0,65000090-001
新北市三峽區中埔里,新北市,三峽區,中埔里,4.104684,0.5,0.1,0.5,0.2,0.0,0.0,65000090-004
新北市三峽區中正里,新北市,三峽區,中正里,2.616301,0.3,0.1,0.3,0.1,0.0,0.0,65000090-025
新北市三峽區二鬮里,新北市,三峽區,二鬮里,0.260117,0.2,0.1,0.3,0.1,0.0,0.0,65000090-026
新北市三峽區五寮里,新北市,三峽區,五寮里,0.615132,0.1,0.5,0.4,0.1,0.0,0.0,65000090-014
...,...,...,...,...,...,...,...,...,...,...,...
臺北市萬華區錦德里,臺北市,萬華區,錦德里,2.621979,0.3,0.4,0.1,0.2,0.0,0.0,63000070-025
臺北市萬華區雙園里,臺北市,萬華區,雙園里,3.975695,0.4,0.3,0.2,0.4,0.0,0.0,63000070-012
臺北市萬華區青山里,臺北市,萬華區,青山里,3.742633,0.2,0.4,0.4,0.3,0.0,0.0,63000070-006
臺北市萬華區頂碩里,臺北市,萬華區,頂碩里,2.571129,0.2,0.4,0.1,0.3,0.0,0.0,63000070-011
臺北市萬華區騰雲里,臺北市,萬華區,騰雲里,4.404452,0.2,0.5,0.3,0.3,0.0,0.0,63000070-036

In [23]:
qol.to_csv("qol109score.csv")